version: '3'
services:
   mariadb:
      env_file:
         - .env
      build: ./requirements/mariadb
      container_name: mariadb
      image: mariadb
      restart: always
      ports:
         - "3306:3306"
      volumes:
         - mariadb_data:/var/lib/mysql
      networks:
         - my_network
   wordpress:
      env_file:
         - .env
      build: ./requirements/wordpress
      container_name: wordpress
      image: wordpress
      depends_on:
         - mariadb
      restart: always
      ports:
         - "9000:9000"
      volumes:
         - wordpress_data:/var/www/html
      networks:
         - my_network
   redis:
      build: ./requirements/bonus/redis
      container_name: redis
      image: redis
      restart: always
      depends_on:
         - wordpress
      ports:
         - "6379:6379"
      networks:
         - my_network
   nginx:
      build: ./requirements/nginx
      container_name: nginx
      image: nginx
      depends_on:
         - wordpress
      ports:
         - "443:443"
      volumes:
         - wordpress_data:/var/www/html
      networks:
         - my_network
      restart: always
   adminer:
      build: ./requirements/bonus/adminer
      container_name: adminer
      image: adminer
      restart: always
      ports:
         - "8000:8000"
      depends_on:
         - mariadb
      networks:
         - my_network
   static_web:
      build: ./requirements/bonus/static_web
      container_name: static_web
      image: static_web
      restart: always
      ports:
         - "8080:8080"
      networks:
         - my_network
volumes:
   wordpress_data:
      driver: local
      driver_opts:
         type: none
         o: bind
         device: /home/sriyani/data/WordPress
   mariadb_data:
      driver: local
      driver_opts:
         type: none
         o: bind
         device: /home/sriyani/data/DB
networks:
  my_network:
    driver: bridge
