FROM debian:buster

RUN apt-get -y update && apt-get install php-redis php-fpm -y php-mysql && apt install curl -y 

COPY www.conf etc/php/7.3/fpm/pool.d

COPY /tools/script.sh  .

RUN chmod +x script.sh

ENTRYPOINT [ "sh","script.sh"] 

CMD ["/usr/sbin/php-fpm7.3" ,"-F"]

