
FROM debian:buster

RUN apt-get -y update 

RUN apt-get -y install nginx

COPY default /etc/nginx/sites-available/default

COPY certificate/my-site.crt /etc/ssl/certs/nginx-selfsigned.crt

COPY certificate/my-site.key /etc/ssl/private/nginx-selfsigned.key

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
