
FROM debian:buster

RUN apt-get -y update 

RUN apt-get -y install nginx && apt install systemd -y

COPY static /var/www/html

COPY default /etc/nginx/sites-available/default

RUN service nginx start


EXPOSE 8080


CMD ["nginx", "-g", "daemon off;"]
